<?php 
require_once './templeates/header.phtml';
?>

<form method="POST" action="auth">
  <div class="form-group">
    <label for="usuario">usuario</label>
    <input type="text" class="form-control" id="usuario" name="usuario" placeholder="Usuario">
  </div>
  <div class="form-group">
    <label for="contraseña">Contraseña</label>
    <input type="password" class="form-control" id="contraseña" name="contraseña" placeholder="Contraseña">
  </div>
  <?php if ($message != null): ?>
  <div>
    <p class="text-warning"><?= $message ?></p>
  </div>
  <?php endif ?>
  <button type="submit" class="btn btn-primary">Ingresar</button>
</form>

<?php
require_once './templeates/footer.phtml'; ?>